### ISSUE TITLE
API Endpoint needs to be changed in the documentation

### ISSUE THREAD

**Issue by msrajanadar** [pselker2/WebexTeams-spoke#1]
Hi Team,
Please change the API endpoint from https://api.ciscospark.com to https://webexapis.com in the below documentation

https://github.com/pselker2/WebexTeams-spoke/blob/b8946e5c77b14d7450089ccac55c47eabe103ec0/README.md?plain=1#L89

**Comment by pselker2** [comment]
Updated the README with the current API endpoint.
